apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "consul.fullname" . }}
  labels:
    {{- include "consul.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "consul.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "consul.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "consul.serviceAccountName" . }}
      containers:
      - name: consul-server
        volumeMounts:
        - mountPath: /consul/data
          name: data
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        {{- if .Values.global.imageRegistry }}
        image: "{{ .Values.global.imageRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- else }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: consul
            containerPort: 8500
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: consul
        readinessProbe:
          tcpSocket:
            port: consul
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: consul-data
