apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consul-data 
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.global.storageClassName }}
  storageClassName: {{ .Values.global.storageClassName }}
  {{- else }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
